# Duplicates deploy settings in ci.yml. Required for some reason, or the Netlify deploys
# time out and/or hit 500 errors.
[build]
  functions = "dist/functions"
  publish = "dist/public"

# Host all functions under /api:
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
